# Generated by Django 4.2.1 on 2023-06-26 07:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='likededby',
        ),
        migrations.AddField(
            model_name='likes',
            name='likededby',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
