# Generated by Django 4.2.1 on 2023-06-26 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_likes_likededby_likes_likededby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='likededby',
        ),
        migrations.AddField(
            model_name='likes',
            name='likededby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
