# Generated by Django 4.2.1 on 2023-06-26 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_likes_likededby_alter_likes_postinaccount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='followedby',
            new_name='follows',
        ),
        migrations.AddField(
            model_name='following',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='havelikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
