# Generated by Django 4.2.1 on 2023-06-26 20:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_remove_following_follows_alter_following_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='follows',
        ),
        migrations.AddField(
            model_name='following',
            name='follows',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
